{
  "data"[
    ({
      name: "UltraSoft Towel",
      category: "Home Essentials",
      price: 25.99,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/PjReSjG",
      rating: 4.5,
      description:
        "Woven from the silken threads of the Moonspider, enchanted to absorb the tears of both sorrow and joy, leaving the user's skin mystically refreshed.",
    },
    {
      name: "Eco-Friendly Water Bottle",
      category: "Fitness",
      price: 15.75,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/AwvFAZN",
      rating: 4.8,
      description:
        "Forged from the heart of an ancient glacier, this vessel contains the essence of a thousand winters, cooling its contents with the whisper of the North Wind.",
    },
    {
      name: "Wireless Earbuds",
      category: "Electronics",
      price: 89.99,
      inStock: false,
      quantity: 10,
      imageUrl: "https://imgur.com/6cFehBe",
      rating: 4.4,
      description:
        "Carved from obsidian, these earbuds are tuned by the sirens' song, channeling the arcane frequencies of the ether to the listener's ears.",
    },
    {
      name: "Organic Green Tea",
      category: "Groceries",
      price: 5.49,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/BR6kkRy",
      rating: 4.6,
      description:
        "Brewed with leaves plucked by moonlit dryads from the ancient Tea Groves of Eld, imbued with the power to soothe the most tumultuous souls.",
    },
    {
      name: "Smart Fitness Watch",
      category: "Fitness",
      price: 199.99,
      inStock: false,
      quantity: 10,
      imageUrl: "https://imgur.com/taU1hZP",
      rating: 4.2,
      description:
        "A timepiece crafted from the remains of a fallen star, tracking the movements of its bearer with celestial precision, guided by the spirits of old.",
    },
    {
      name: "Professional Blender",
      category: "Kitchen Appliances",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/JhaVPxS",
      rating: 4.7,
      description:
        "A device powered by a bound elemental, capable of transmuting raw ingredients into elixirs and potions, blending the very essence of nature itself.",
    },
    {
      name: "Bluetooth Speaker",
      category: "Electronics",
      price: 59.99,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/slTbgx9",
      rating: 4.3,
      description:
        "Encased in dragon scales, this speaker amplifies the ancient hymns of the earth, summoning forth sound with a clarity and depth unheard by mortal ears.",
    },
    {
      name: "Scented Candle Set",
      category: "Home Decor",
      price: 29.99,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/bSpYFSG",
      rating: 4.9,
      description:
        "Candles made from the wax of twilight bees, each flame flickers with scents gathered from the dreams of sleeping nymphs, filling the air with enchanted aromas.",
    },
    {
      name: "Gourmet Chocolate Box",
      category: "Groceries",
      price: 19.99,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/NamLeL9",
      rating: 4.5,
      description:
        "Confections conjured from the shadows of the Enchanted Forest, sweetened by the forbidden fruits of the Underworld, offering a taste of dark, mystical delights.",
    },
    {
      name: "Leather Wallet",
      category: "Accessories",
      price: 49.99,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/4aV0fVu",
      rating: 4.0,
      description:
        "Crafted from the hide of a chimeric beast, enchanted to guard the wealth of its bearer, multiplying any coin placed within by the light of the full moon.",
    },
    {
      name: "Enchanted Quill",
      category: "Stationery",
      price: 45.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/LAx7S0W",
      rating: 4.7,
      description:
        "Feathered quill from a phoenix's tail, dipped in ink brewed from the essence of nightshade. Writes with a script that glows under the moonlight.",
    },
    {
      name: "Shadow Cloak",
      category: "Apparel",
      price: 130.5,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/ZNGLCaT",
      rating: 4.9,
      description:
        "Woven from the dark mist of the void, this cloak grants its wearer the ability to blend into shadows, becoming nearly invisible to the naked eye.",
    },
    {
      name: "Arcane Lantern",
      category: "Home Decor",
      price: 60.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/mNfA0zh",
      rating: 4.3,
      description:
        "A lantern holding a trapped will-o'-the-wisp, casting an ethereal light that reveals the unseen truths of the world.",
    },
    {
      name: "Mystic Tome",
      category: "Books",
      price: 200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/hFvFmo1",
      rating: 4.8,
      description:
        "A book bound in dragon hide, containing the lost spells and prophecies of ancient mages, readable only by those with the gift of the second sight.",
    },
    {
      name: "Potion of Healing",
      category: "Health",
      price: 35.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/HDnzsRb",
      rating: 4.6,
      description:
        "Brewed from the dew of sun-kissed mushrooms and the essence of moonflowers, this potion restores vitality and mends wounds with a single drop.",
    },
    {
      name: "Crystal Ball",
      category: "Occult",
      price: 75.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Sj0oRvh",
      rating: 4.4,
      description:
        "Forged from the crystalized tears of a banshee, this orb allows the beholder to glimpse into the future, albeit through riddles and shadows.",
    },
    {
      name: "Silver Dagger",
      category: "Weapons",
      price: 95.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Zca6slq",
      rating: 4.7,
      description:
        "Crafted under a blood moon, this blade can pierce the veil between worlds, banishing spirits and demons back to the ether.",
    },
    {
      name: "Elixir of Wisdom",
      category: "Beverages",
      price: 40.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/8dviZfi",
      rating: 4.5,
      description:
        "A vial of liquid distilled from the minds of ancient scholars, imbibing it grants the drinker profound insights and knowledge.",
    },
    {
      name: "Rune Stones",
      category: "Occult",
      price: 50.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/AQNYwcy",
      rating: 4.2,
      description:
        "Stones carved with the ancient runes of power, each throw divines the future, casting light on what is hidden in shadow.",
    },
    {
      name: "Phantom Mirror",
      category: "Home Decor",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/WX2DurO",
      rating: 4.0,
      description:
        "A mirror framed with bones, showing not just the reflection, but the true soul of whoever dares to gaze into it, revealing secrets long buried.",
    },
    {
      name: "Amulet of Protection",
      category: "Accessories",
      price: 85.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/v5N611J",
      rating: 4.8,
      description:
        "Forged from the scales of a wyvern, this amulet shields its bearer from dark magics and curses, humming softly with an ancient spell of warding.",
    },
    {
      name: "Ring of the Phoenix",
      category: "Accessories",
      price: 150.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/2nBuOFi",
      rating: 4.9,
      description:
        "A silver ring adorned with a phoenix feather, imbued with the fiery essence of rebirth, granting its wearer the power to rise anew from despair.",
    },
    {
      name: "Obsidian Cufflinks",
      category: "Accessories",
      price: 70.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/LR4TPLk",
      rating: 4.5,
      description:
        "Carved from volcanic glass, these cufflinks are enchanted to anchor the wearer firmly to the earth, providing stability in tumultuous times.",
    },
    {
      name: "Ethereal Scarf",
      category: "Accessories",
      price: 95.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/tNRf5ri",
      rating: 4.7,
      description:
        "Woven from the gossamer threads of fairy silk, this scarf shimmers with an otherworldly glow, cloaking the wearer in a veil of mystery.",
    },
    {
      name: "Gloves of Thievery",
      category: "Accessories",
      price: 110.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/XvTJMBu",
      rating: 4.6,
      description:
        "Crafted from the skin of a shadow leopard, these gloves render the wearer's hands invisible, perfect for pilfering treasures unseen.",
    },
    {
      name: "Belt of the Berserker",
      category: "Accessories",
      price: 130.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Efb8jWf",
      rating: 4.4,
      description:
        "A leather belt imbued with the spirit of a wild bear, granting the wearer unmatched strength and ferocity in the heat of battle.",
    },
    {
      name: "Boots of Elvenkind",
      category: "Accessories",
      price: 140.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/10CuTLC",
      rating: 4.8,
      description:
        "Soft leather boots that tread silently, a gift from the elves, allowing the wearer to move unseen and unheard by mortal ears.",
    },
    {
      name: "Pendant of Time",
      category: "Accessories",
      price: 200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/SZWGUU6",
      rating: 4.9,
      description:
        "Containing a shard of crystal from the Sands of Time, this pendant allows its wearer brief glimpses into the past and future, revealing the flow of destiny.",
    },
    {
      name: "Bracelet of Binding",
      category: "Accessories",
      price: 60.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/eHUKk5b",
      rating: 4.3,
      description:
        "A chain bracelet that binds two souls together, allowing them to feel each other's emotions and thoughts, no matter the distance that separates them.",
    },
    {
      name: "Crown of the Forest",
      category: "Accessories",
      price: 175.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/mLL3xVX",
      rating: 5.0,
      description:
        "A circlet made from the oldest oak, adorned with leaves that never wither. It grants the wearer dominion over the natural elements, commanding respect from all creatures.",
    },
    {
      name: "Robes of the Arcanist",
      category: "Apparel",
      price: 250.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/NMtXGbb",
      rating: 4.9,
      description:
        "Woven with the silk of ethereal spiders, these robes are imbued with arcane energy, amplifying the magical abilities of the wearer.",
    },
    {
      name: "Vestments of the Shadow",
      category: "Apparel",
      price: 220.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/PMPmGsn",
      rating: 4.8,
      description:
        "Forged in darkness and whispered curses, these vestments grant the wearer the ability to meld into shadows, becoming as intangible as the night.",
    },
    {
      name: "Boots of Swift Passage",
      category: "Apparel",
      price: 180.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/FABUaXW",
      rating: 4.7,
      description:
        "Crafted by the wind sprites, these boots allow the wearer to move with the speed of a gale, leaving only a whisper in their wake.",
    },
    {
      name: "Cape of the Phoenix",
      category: "Apparel",
      price: 300.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/q7a9oYG",
      rating: 5.0,
      description:
        "Infused with the essence of a phoenix's rebirth, this cape shields its bearer from mortal harm, resurrecting them from the brink of death.",
    },
    {
      name: "Gauntlets of Power",
      category: "Apparel",
      price: 160.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Nx8Pz9z",
      rating: 4.6,
      description:
        "Forged in dragonfire and cooled in the blood of a titan, these gauntlets bestow unmatched strength upon the hands that wield them.",
    },
    {
      name: "Mask of the Seer",
      category: "Apparel",
      price: 90.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/TxRkUuc",
      rating: 4.5,
      description:
        "Carved from the bone of a clairvoyant beast, this mask grants visions of truth to those who wear it, piercing through lies and deceit.",
    },
    {
      name: "Breeches of Endurance",
      category: "Apparel",
      price: 140.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/IlRAUmp",
      rating: 4.4,
      description:
        "Stitched by the nomads of the eternal desert, these breeches grant the wearer resilience against the harshest of elements and trials.",
    },
    {
      name: "Hood of Whispering Shadows",
      category: "Apparel",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/x9pjXlo",
      rating: 4.7,
      description:
        "Woven from the fabric of night itself, this hood whispers secrets of the dark to its bearer, concealing their presence from unfriendly eyes.",
    },
    {
      name: "Gloves of the Minstrel",
      category: "Apparel",
      price: 75.0,
      inStock: true,
      quantity: 10,

      imageUrl: "https://imgur.com/Ez9EuIk",
      rating: 4.3,
      description:
        "Sewn from the petals of the twilight rose, these gloves enchant the wearer's touch, turning every gesture into a spellbinding melody.",
    },
    {
      name: "Tunic of the Druid",
      category: "Apparel",
      price: 210.0,
      inStock: true,
      quantity: 10,

      imageUrl: "https://imgur.com/idFKdUk",
      rating: 4.8,
      description:
        "Embroidered with the ancient runes of the earth, this tunic binds the wearer to the land, allowing them to draw upon its life force.",
    },
    {
      name: "Parchment of Eldritch Lore",
      category: "Stationery",
      price: 45.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/gVzk8l0",
      rating: 4.8,
      description:
        "Sheets of parchment harvested from the bewitched Elder Tree, inscribed upon which words whisper forbidden knowledge to those deemed worthy.",
    },
    {
      name: "Ink of the Abyss",
      category: "Stationery",
      price: 70.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/CaDN3zJ",
      rating: 4.9,
      description:
        "Ink drawn from the depths of the Nether Sea, dark as a starless night and capable of revealing secrets hidden to the naked eye under moonlight.",
    },
    {
      name: "Sealing Wax of Binding",
      category: "Stationery",
      price: 30.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/vGqsmDZ",
      rating: 4.6,
      description:
        "Wax imbued with the essence of an ancient pact, its seal unbreakable by any known magic, ensuring the contents remain untouched until reaching their destined hand.",
    },
    {
      name: "Quill of the Raven",
      category: "Stationery",
      price: 55.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/8pwDBQu",
      rating: 4.7,
      description:
        "A quill fashioned from the feather of a raven that once served as a familiar to a legendary sorcerer, granting insight and inspiration to the writer.",
    },
    {
      name: "Grimoire Notebook",
      category: "Stationery",
      price: 100.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/fAYb4v7",
      rating: 4.9,
      description:
        "A leather-bound notebook that captures thoughts and spells within its pages, safeguarding them from prying eyes with a curse of silence.",
    },
    {
      name: "Enchanted Bookmarks",
      category: "Stationery",
      price: 25.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/rOdFMS0",
      rating: 4.5,
      description:
        "Bookmarks that bind themselves to the soul of the book, guiding the reader back to where they left off with a faint, glowing trail.",
    },
    {
      name: "Mystic Eraser",
      category: "Stationery",
      price: 15.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/dj8V0uc",
      rating: 4.4,
      description:
        "An eraser that doesn't just remove pencil marks but the memories of what was written, allowing for the rewriting of history in the hands of its user.",
    },
    {
      name: "Spellbinding Paper Clips",
      category: "Stationery",
      price: 10.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/hQ8hgw4",
      rating: 4.3,
      description:
        "Paper clips forged in the fires of Mount Dread, each clip holds pages together with an unbreakable magical bond.",
    },
    {
      name: "Featherweight Notebook",
      category: "Stationery",
      price: 35.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/yl2maTg",
      rating: 4.7,
      description:
        "A notebook as light as air, made from the feathers of the Sky Serpents, allowing it to be carried without burden, no matter how many pages are filled.",
    },
    {
      name: "Desk Lamp of Enlightenment",
      category: "Stationery",
      price: 80.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/x6Qe9Ru",
      rating: 4.8,
      description:
        "A lamp that illuminates not just the desk but the mind of the one who studies beneath its light, revealing truths previously obscured in shadow.",
    },
    {
      name: "Sword of the Cosmos",
      category: "Ultra Gear",
      price: 10000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/0WUzKeb",
      rating: 5.0,
      description:
        "Forged in the core of a dying star, this sword slices through the fabric of reality itself, allowing the wielder to command the forces of the cosmos.",
    },
    {
      name: "Crown of Eternal Dominion",
      category: "Ultra Gear",
      price: 15000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/19OzG1a",
      rating: 5.0,
      description:
        "A crown that bestows upon its wearer the wisdom of all who have ruled before, bending the will of both the living and the spectral to its command.",
    },
    {
      name: "Amulet of Infinite Realms",
      category: "Ultra Gear",
      price: 12000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Uh8aPhB",
      rating: 5.0,
      description:
        "An amulet that grants the bearer the ability to traverse dimensions at will, unlocking secrets and powers from infinite realms.",
    },
    {
      name: "Gauntlets of Titan Strength",
      category: "Ultra Gear",
      price: 8000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/42ih8jd",
      rating: 5.0,
      description:
        "Gauntlets that endow the wearer with the strength of a hundred titans, shattering mountains with a single blow and altering the course of rivers.",
    },
    {
      name: "Boots of the Phantom Walker",
      category: "Ultra Gear",
      price: 9000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/iKKyhKO",
      rating: 5.0,
      description:
        "These boots allow the wearer to walk through walls, across water, and float on air, leaving no trace nor stirring a single blade of grass.",
    },
    {
      name: "Robes of the Archmage",
      category: "Ultra Gear",
      price: 11000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/0FMzlg1",
      rating: 5.0,
      description:
        "Robes that amplify magical abilities a thousandfold, turning even the most trivial incantations into world-altering spells.",
    },
    {
      name: "Orb of the Dragon's Heart",
      category: "Ultra Gear",
      price: 13000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/q4CveLW",
      rating: 5.0,
      description:
        "An orb pulsating with the life force of the first dragon, granting its holder command over fire, time, and the ancient language of dragons.",
    },
    {
      name: "Staff of the World Tree",
      category: "Ultra Gear",
      price: 14000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/viAhFd2",
      rating: 5.0,
      description:
        "A staff carved from the World Tree itself, its roots tapping into the essence of life, allowing the wielder to heal or ravage lands with but a thought.",
    },
    {
      name: "Shield of the Ancients",
      category: "Ultra Gear",
      price: 7500.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/tM8QOOx",
      rating: 5.0,
      description:
        "A shield that absorbs any attack, converting the energy into life force for the bearer, and can unleash a devastating counterstrike upon command.",
    },
    {
      name: "Mantle of the Night Sky",
      category: "Ultra Gear",
      price: 8500.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/rEC6T7I",
      rating: 5.0,
      description:
        "A cloak woven from the very essence of the night sky, cloaking the wearer in shadows and stars, making them one with the universe and untouchable by mortal hands.",
    },
    {
      name: "Lantern of Endless Flames",
      category: "Home Decor",
      price: 400.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/bxOkhSM",
      rating: 5.0,
      description:
        "A lantern that burns without fuel, its flame conjured from the eternal fires of the underworld, casting shadows that dance with forgotten tales.",
    },
    {
      name: "Mirror of True Reflection",
      category: "Home Decor",
      price: 450.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/8y7JbJ9",
      rating: 5.0,
      description:
        "A mirror that reveals not just the physical form, but the true essence of one's soul, offering insights into hidden desires and untold futures.",
    },
    {
      name: "Tapestry of the World's Dawn",
      category: "Home Decor",
      price: 1000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/zFtw68E",
      rating: 5.0,
      description:
        "A tapestry depicting the creation of the universe, woven with threads of light itself, shimmering with the magic of the cosmos.",
    },
    {
      name: "Chalice of the Eternal Harvest",
      category: "Home Decor",
      price: 400.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/8yBBQzS",
      rating: 5.0,
      description:
        "A chalice that overflows with ambrosia once every full moon, granting those who drink from it vigor and vitality beyond mortal limits.",
    },
    {
      name: "Statue of the Guardian",
      category: "Home Decor",
      price: 600.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/VQf5dAM",
      rating: 5.0,
      description:
        "A statue carved from meteorite, imbued with the spirit of a celestial guardian, offering protection to all who dwell within its presence.",
    },
    {
      name: "Rug of Whispering Sands",
      category: "Home Decor",
      price: 500.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/uAPwmbt",
      rating: 5.0,
      description:
        "A rug that sings the songs of ancient deserts, its grains telling tales of lost civilizations and guiding the listener through visions of ages past.",
    },
    {
      name: "Vase of the Bound Djinn",
      category: "Home Decor",
      price: 700.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/zte7QoJ",
      rating: 5.0,
      description:
        "A vase containing a djinn bound by ancient magic, granting wishes to those who know the secret words, but always with a twist of fate.",
    },
    {
      name: "Candelabra of the Phantom Light",
      category: "Home Decor",
      price: 600.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/0KBNYGt",
      rating: 5.0,
      description:
        "A candelabra that holds no candles but lights up with ghostly flames, illuminating the room with the soft glow of spirits long gone.",
    },
    {
      name: "Clock of the Timeless Realm",
      category: "Home Decor",
      price: 900.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/LobpLjS",
      rating: 5.0,
      description:
        "A clock that does not measure time but manipulates it, allowing the dweller to stretch moments of joy and compress those of sorrow.",
    },
    {
      name: "Fountain of the Mists",
      category: "Home Decor",
      price: 850.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/JssrkTC",
      rating: 5.0,
      description:
        "A fountain that emits a mystical mist, within which visions of potential futures and pasts can be seen, guiding those who gaze into its depths.",
    },
    {
      name: "Goblet of the Night",
      category: "Kitchenware",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/2nZPZAs",
      rating: 4.7,
      description:
        "A black goblet crafted from obsidian, said to have been filled with the elixir of night by a coven of witches under a new moon.",
    },
    {
      name: "Whispering Wind Chime",
      category: "Home Decor",
      price: 85.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Oqmu8lX",
      rating: 4.8,
      description:
        "A chime made from the bones of a mythical bird, singing secrets on the wind for those who know how to listen.",
    },
    {
      name: "Basilisk Eye Necklace",
      category: "Accessories",
      price: 150.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/CogTMwW",
      rating: 4.9,
      description:
        "A necklace featuring a stone that resembles the eye of a basilisk, offering protection and insight, but with a gaze that feels almost alive.",
    },
    {
      name: "Draconic Flame Candle",
      category: "Home Decor",
      price: 60.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/nocXV8x",
      rating: 4.6,
      description:
        "A candle that burns with a flame resembling a dragon's breath, filling the room with a warmth that whispers of ancient fire.",
    },
    {
      name: "Pendant of the Moonshade",
      category: "Jewelry",
      price: 130.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/GkS5wmf",
      rating: 4.7,
      description:
        "A pendant bathed in the light of a thousand moons, offering clarity and calm to those who wander the night.",
    },
    {
      name: "Enchanted Garden Seeds",
      category: "Outdoor",
      price: 45.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/SUqvuFy",
      rating: 4.8,
      description:
        "Seeds for a garden that blooms overnight under the glow of the moon, with flowers that whisper lullabies to the weary.",
    },
    {
      name: "Wand of the Forgotten",
      category: "Collectibles",
      price: 220.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/XRwdtgT",
      rating: 4.9,
      description:
        "A wand made from wood that remembers the ancient magics of the world, stirring memories of power in those who wield it.",
    },
    {
      name: "Book of Shadows Journal",
      category: "Stationery",
      price: 95.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/RauneF0",
      rating: 4.7,
      description:
        "A journal bound in shadows, its pages filled with the potential to capture the darkest of spells and the deepest of thoughts.",
    },
    {
      name: "Eternal Night Bedspread",
      category: "Home Essentials",
      price: 175.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Fjz7Mdp",
      rating: 4.8,
      description:
        "A bedspread woven from the very essence of night, enveloping sleepers in dreams that walk the line between darkness and light.",
    },
    {
      name: "Phantasmal Light Fixture",
      category: "Lighting",
      price: 200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/ociOAOa",
      rating: 4.6,
      description:
        "A light fixture that illuminates with a ghostly glow, casting shapes and shadows that move with a life of their own.",
    },
    {
      name: "Spectral Sound System",
      category: "Electronics",
      price: 350.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/H0xmIVQ",
      rating: 4.8,
      description:
        "A sound system that channels the acoustics of the netherworld, creating an auditory experience filled with haunting melodies and ethereal whispers.",
    },
    {
      name: "Arcanum Smart Watch",
      category: "Electronics",
      price: 400.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/YOmXwhq",
      rating: 4.9,
      description:
        "A smartwatch forged in enchanted silver, capable of predicting the future with cryptic notifications and tracking the phases of the moon.",
    },
    {
      name: "Phantom Projector",
      category: "Electronics",
      price: 500.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/WbWvkPf",
      rating: 4.7,
      description:
        "A projector that displays images from other realms, turning any room into a portal to landscapes filled with mythical creatures and ancient ruins.",
    },
    {
      name: "Grimoire Tablet",
      category: "Electronics",
      price: 300.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/dgncTOJ",
      rating: 4.8,
      description:
        "A tablet that resembles an ancient grimoire, with apps for casting digital spells and summoning virtual familiars to aid in daily tasks.",
    },
    {
      name: "Ethereal E-Reader",
      category: "Electronics",
      price: 250.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/NCMeEnv",
      rating: 4.6,
      description:
        "An e-reader that glows with an otherworldly light, capable of downloading books from the past, present, and future, across all dimensions.",
    },
    {
      name: "Shadow Drone",
      category: "Electronics",
      price: 750.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/MEf0881",
      rating: 4.9,
      description:
        "A drone that flies silently in the shadows, capturing footage from the unseen world, revealing secrets hidden from the human eye.",
    },
    {
      name: "Wraith Wireless Charger",
      category: "Electronics",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/fAQ3uFY",
      rating: 4.7,
      description:
        "A wireless charger that siphons energy from the ether, charging devices with the efficiency of a lightning strike and the whisper of ancient incantations.",
    },
    {
      name: "Banshee Bluetooth Headphones",
      category: "Electronics",
      price: 180.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Ki13xJL",
      rating: 4.8,
      description:
        "Headphones that let you hear the unhearable, from the softest footsteps of spirits to the distant cries of banshees, with crystal clear sound.",
    },
    {
      name: "Necromancer's Night Light",
      category: "Electronics",
      price: 100.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/kkcYOpq",
      rating: 4.5,
      description:
        "A night light that emits a gentle, soothing glow, rumored to be powered by the captured essence of will-o'-the-wisps.",
    },
    {
      name: "Enchanted Gaming Console",
      category: "Electronics",
      price: 400.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/IfbUaMI",
      rating: 4.9,
      description:
        "A gaming console that transports players into the game world, making every adventure and battle feel as real as life itself, with magic at the player's fingertips.",
    },
    {
      name: "Shadowstep Running Shoes",
      category: "Fitness",
      price: 150.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/1EpVRIx",
      rating: 4.8,
      description:
        "Shoes crafted from the hide of a nocturnal beast, granting the wearer the ability to run with the silence and swiftness of a shadow.",
    },
    {
      name: "Phoenix Feather Yoga Mat",
      category: "Fitness",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/qUmkGBf",
      rating: 4.9,
      description:
        "A yoga mat woven from the feathers of a phoenix, imbuing the user with rejuvenating warmth and the resilience of rebirth through each pose.",
    },
    {
      name: "Golem's Strength Training Set",
      category: "Fitness",
      price: 200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/vaubJmz",
      rating: 4.7,
      description:
        "A set of weights forged in the heart of a mountain, each lift imbues the user with the unstoppable force of a golem.",
    },
    {
      name: "Mermaid's Aquatic Treadmill",
      category: "Fitness",
      price: 1000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/XjmQM1e",
      rating: 4.8,
      description:
        "An underwater treadmill that allows for the grace and resistance of swimming without the need for a pool, guided by the enchantment of mermaids.",
    },
    {
      name: "Vampire's Endurance Elliptical",
      category: "Fitness",
      price: 800.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/fiiWSgT",
      rating: 4.6,
      description:
        "An elliptical machine that draws on the night's energy, offering workouts that increase endurance to supernatural levels.",
    },
    {
      name: "Warrior's Battle Ropes",
      category: "Fitness",
      price: 110.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/iEZx9VD",
      rating: 4.9,
      description:
        "Ropes that resonate with the spirit of ancient warriors, enhancing the user's strength and agility as if preparing for mythical battle.",
    },
    {
      name: "Sorcerer's Spell Resistance Bands",
      category: "Fitness",
      price: 85.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/UxAZNxj",
      rating: 4.7,
      description:
        "Resistance bands imbued with magical force, challenging the user with opposition that adapts and strengthens their mystical defenses.",
    },
    {
      name: "Dragon's Breath Kettlebell",
      category: "Fitness",
      price: 130.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/pdjDsRX",
      rating: 4.8,
      description:
        "A kettlebell that glows hotter with each swing, stoking the inner fire of the user, burning calories as fiercely as dragon's breath.",
    },
    {
      name: "Griffin's Wing Glider",
      category: "Fitness",
      price: 950.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Vwn9JJe",
      rating: 4.9,
      description:
        "A hang glider designed with the majesty of a griffin's wings, offering the thrill of flight and the freedom to soar through the skies.",
    },
    {
      name: "Lycanthrope's Full Moon Tracker",
      category: "Fitness",
      price: 170.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/WEkuzeY",
      rating: 4.7,
      description:
        "A fitness tracker that harnesses the power of the full moon, enhancing physical abilities and tracking nocturnal activities with supernatural precision.",
    },
    {
      name: "Eternal Flame Lantern",
      category: "Home Essentials",
      price: 95.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/hrYfWeu",
      rating: 4.7,
      description:
        "A lantern that houses an eternal flame, never needing fuel, casting a warm, inviting glow that wards off shadows and creatures of the night.",
    },
    {
      name: "Goblin-crafted Cutlery Set",
      category: "Home Essentials",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/oCa71gG",
      rating: 4.8,
      description:
        "A set of cutlery forged in goblin fires, durable and sharp, with a magic that makes every meal taste like a feast in a mythical hall.",
    },
    {
      name: "Mystic Springs Water Filter",
      category: "Home Essentials",
      price: 150.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/sdD57g0",
      rating: 4.9,
      description:
        "A water filter sourced from the mystic springs, purifying water to taste as if drawn directly from a magical well, imbued with healthful energies.",
    },
    {
      name: "Fey-inspired Bed Linen",
      category: "Home Essentials",
      price: 200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/WOccPVI",
      rating: 4.6,
      description:
        "Bed linen inspired by the Fey, woven from the finest silks that change color with the moon's phase, ensuring dreams filled with enchantment.",
    },
    {
      name: "Arcane Alarm Clock",
      category: "Home Essentials",
      price: 80.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/EuOhiWy",
      rating: 4.8,
      description:
        "An alarm clock that awakens you with a gentle arcane melody, lifting the veil of sleep with a whisper of magic rather than a jarring sound.",
    },
    {
      name: "Enchanted Tea Kettle",
      category: "Home Essentials",
      price: 110.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/CuDXNv6",
      rating: 4.7,
      description:
        "A tea kettle that whistles with the voices of the ancients, boiling water with an inner flame that requires no external heat source.",
    },
    {
      name: "Witch's Brew Coffee Maker",
      category: "Home Essentials",
      price: 250.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/LJwuzDt",
      rating: 4.9,
      description:
        "A coffee maker that brews with a touch of witchcraft, ensuring the perfect cup every time, infused with spells for energy and clarity.",
    },
    {
      name: "Spectral Light Bulbs",
      category: "Home Essentials",
      price: 70.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/7mErfRO",
      rating: 4.5,
      description:
        "Light bulbs that cast a soft, ethereal glow, illuminating rooms with a light that seems to shimmer with spectral energy.",
    },
    {
      name: "Draconic Heat Blanket",
      category: "Home Essentials",
      price: 180.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/j3cYx0N",
      rating: 4.7,
      description:
        "A heat blanket imbued with the warmth of dragonfire, offering comfort and protection from the coldest of nights with a gentle, enduring warmth.",
    },
    {
      name: "Elemental Air Purifier",
      category: "Home Essentials",
      price: 300.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/gJ6KOKc",
      rating: 4.8,
      description:
        "An air purifier that harnesses the power of elemental air spirits, cleansing the atmosphere of pollutants and imbuing the home with the freshness of a pristine forest.",
    },
    {
      name: "Elixir of Vitality Juice",
      category: "Groceries",
      price: 15.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/lc1l8Ig",
      rating: 4.7,
      description:
        "A refreshing juice blend made from the rarest fruits of enchanted forests, known to restore vitality and invigorate the soul.",
    },
    {
      name: "Chimera Meat Pack",
      category: "Groceries",
      price: 50.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/eQjhN5Q",
      rating: 4.8,
      description:
        "Exotic meats from mythical chimeras, offering a taste of the wild magic that pulses through their veins. Perfect for a feast of heroes.",
    },
    {
      name: "Dragonfruit of Endurance",
      category: "Groceries",
      price: 20.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/VZFJVE5",
      rating: 4.9,
      description:
        "A dragonfruit blessed by ancient dragons, granting those who consume it increased endurance and strength on their quests.",
    },
    {
      name: "Nectar of the Gods Honey",
      category: "Groceries",
      price: 25.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/eILjR9w",
      rating: 4.6,
      description:
        "Honey collected from the hives of celestial bees, sweet enough to enchant the palate and heal the wounds of the weary.",
    },
    {
      name: "Mystical Mushroom Mix",
      category: "Groceries",
      price: 30.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/SVuqGlm",
      rating: 4.7,
      description:
        "A blend of mushrooms harvested under a full moon, imbued with properties that can illuminate the mind and enhance visions.",
    },
    {
      name: "Phoenix Eggs",
      category: "Groceries",
      price: 45.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/ViSeY8Q",
      rating: 5.0,
      description:
        "Eggs laid by the legendary phoenix, known to possess the power to rejuvenate and invigorate those who partake of them.",
    },
    {
      name: "Goblin Grown Greens",
      category: "Groceries",
      price: 10.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/eRPdIzz",
      rating: 4.5,
      description:
        "Vegetables cultivated in the gardens of goblins, where the soil is enriched with magic, yielding produce of unparalleled taste and nutrition.",
    },
    {
      name: "Ambrosia Salad Kit",
      category: "Groceries",
      price: 35.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/XajnfTu",
      rating: 4.8,
      description:
        "A kit for making ambrosia salad, said to be the food of the gods, with ingredients that sparkle with a hint of divine essence.",
    },
    {
      name: "Lycan's Choice Meat Selection",
      category: "Groceries",
      price: 60.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/xUlWa86",
      rating: 4.9,
      description:
        "A selection of meats curated for the strength and vitality of a werewolf, perfect for those nights when the moon is full and hunger strikes.",
    },
    {
      name: "Enchanted Espresso Beans",
      category: "Groceries",
      price: 18.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/2Pxzyju",
      rating: 4.7,
      description:
        "Espresso beans kissed by moonlight and enchanted by night fairies, brewing a coffee that awakens the soul with each sip.",
    },
    {
      name: "Cauldron of Endless Stews",
      category: "Kitchen Appliances",
      price: 300.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/jUZNdUb",
      rating: 4.8,
      description:
        "A mystical cauldron that simmers stews and soups to perfection, with a magical ability to never boil over, conjuring flavors from across the realms.",
    },
    {
      name: "Inferno Toaster",
      category: "Kitchen Appliances",
      price: 150.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/MYTCw6R",
      rating: 4.7,
      description:
        "A toaster imbued with the essence of dragon breath, toasting bread with the perfect crispness, adorned with scorched designs of ancient runes.",
    },
    {
      name: "Frostbinder Refrigerator",
      category: "Kitchen Appliances",
      price: 1200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/jV4OZKi",
      rating: 4.9,
      description:
        "A refrigerator that uses the power of elemental ice spirits to keep food fresh, featuring a frost magic setting for instant chilling of drinks.",
    },
    {
      name: "Spectral Blender",
      category: "Kitchen Appliances",
      price: 220.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/KZpCNqF",
      rating: 4.8,
      description:
        "A blender that operates in silence, blending ingredients with ghostly efficiency, capable of summoning ethereal flavors from thin air.",
    },
    {
      name: "Alchemy Coffee Maker",
      category: "Kitchen Appliances",
      price: 250.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/L7uE9Tb",
      rating: 4.9,
      description:
        "A coffee maker that brews potions as easily as coffee, transforming water and beans into elixirs that energize the body and enlighten the mind.",
    },
    {
      name: "Amulet of Whispering Shadows",
      category: "Jewelry",
      price: 200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/qxN1e24",
      rating: 4.9,
      description:
        "An amulet encrusted with a dark gem that whispers secrets of the past and future, glowing softly in the presence of hidden truths.",
    },
    {
      name: "Ring of the Eldritch Knight",
      category: "Jewelry",
      price: 180.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/lp7VNWD",
      rating: 4.8,
      description:
        "A ring forged in the fires of a fallen star, imbued with the courage and strength of ancient knights who walked the realms beyond.",
    },
    {
      name: "Necklace of the Moon Maiden",
      category: "Jewelry",
      price: 220.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/P4Rjk53",
      rating: 4.7,
      description:
        "A silver necklace holding a moonstone pendant, offering protection in the night and enhancing the wearer's connection to the moon's magic.",
    },
    {
      name: "Bracelet of Binding Winds",
      category: "Jewelry",
      price: 160.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/C7zfWX9",
      rating: 4.6,
      description:
        "A bracelet that calls upon the winds of the ancient world, guiding the wearer through storms and providing a shield against unseen forces.",
    },
    {
      name: "Earrings of the Siren's Call",
      category: "Jewelry",
      price: 140.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/jXqnYyl",
      rating: 4.8,
      description:
        "Earrings that resonate with the haunting melody of a siren's call, captivating the hearts of those who hear and granting charisma to the wearer.",
    },
    {
      name: "Crown of the Forest Guardian",
      category: "Jewelry",
      price: 500.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/oiVTN5U",
      rating: 5.0,
      description:
        "A crown woven from the ancient vines and flowers of the oldest forest, empowering the wearer with dominion over nature and its creatures.",
    },
    {
      name: "Pendant of the Arcane Phoenix",
      category: "Jewelry",
      price: 250.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Z8tkMoU",
      rating: 4.9,
      description:
        "A pendant that burns with the essence of the arcane phoenix, rebirthing its wearer from the ashes of despair into the flames of hope.",
    },
    {
      name: "Belt of the Dwarf King",
      category: "Jewelry",
      price: 300.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/SpqTOoD",
      rating: 4.8,
      description:
        "A belt made from the finest dwarven leather, studded with gems that protect the wearer from harm and enhance their craftsmanship.",
    },
    {
      name: "Brooch of the Enchanted Forest",
      category: "Jewelry",
      price: 170.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/rqARsF5",
      rating: 4.7,
      description:
        "A brooch that holds the essence of the enchanted forest, allowing the wearer to commune with trees and wildlife, and to walk unseen through the woods.",
    },
    {
      name: "Tiara of the Celestial Oracle",
      category: "Jewelry",
      price: 450.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/2AuNuOY",
      rating: 5.0,
      description:
        "A tiara that channels the wisdom of the celestial bodies, granting the wearer visions of the future and the wisdom to guide those around them.",
    },
    {
      name: "Cloak of the Wandering Mage",
      category: "Outdoor",
      price: 250.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/0siZgXm",
      rating: 4.9,
      description:
        "A cloak that shields the wearer from the elements, made from fabric that shimmers with an ethereal light, guiding them safely through the darkest woods and the deepest nights.",
    },
    {
      name: "Boots of the Mountain Path",
      category: "Outdoor",
      price: 200.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/Fw3Wopn",
      rating: 4.8,
      description:
        "Boots that adapt to any terrain, enchanted to provide sure footing on the slipperiest slopes and to leave no trace, protecting the sacred paths of the wild.",
    },
    {
      name: "Tent of the Starbound",
      category: "Outdoor",
      price: 600.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/gTMsCrU",
      rating: 5.0,
      description:
        "A tent that unfolds under the night sky, revealing a canvas painted with constellations that glow softly, offering protection and guidance from the stars themselves.",
    },
    {
      name: "Lantern of Everlight",
      category: "Outdoor",
      price: 120.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/aJD15Ir",
      rating: 4.7,
      description:
        "A lantern that burns without oil, casting a gentle light that reveals hidden paths and treasures in the wilderness, while keeping malevolent creatures at bay.",
    },
    {
      name: "Compass of Destiny",
      category: "Outdoor",
      price: 180.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/MfBJHY8",
      rating: 4.9,
      description:
        "A compass that doesn't point north but to the wearer's destiny, guiding adventurers not just through the land but through their life's quest.",
    },
    {
      name: "Quiver of the Phantom Archer",
      category: "Outdoor",
      price: 220.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/ifBwGSe",
      rating: 4.8,
      description:
        "A quiver that provides an endless supply of arrows, each tipped with spectral energy, ensuring the hunter's aim is true and their quarry is noble.",
    },
    {
      name: "Rope of Binding Spirits",
      category: "Outdoor",
      price: 90.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/FT5p3W4",
      rating: 4.6,
      description:
        "A rope that can bind anything, not with strength but with enchantments, capable of holding fast the most elusive of spirits or the fiercest of beasts.",
    },
    {
      name: "Backpack of the Endless Journey",
      category: "Outdoor",
      price: 300.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/EWXSTb9",
      rating: 5.0,
      description:
        "A backpack that carries more than it should, its interior a pocket dimension of infinite space, ensuring no essential is left behind.",
    },
    {
      name: "Map of the Hidden Realms",
      category: "Outdoor",
      price: 350.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/TnoHPDO",
      rating: 5.0,
      description:
        "A map that reveals itself under the moonlight, showing not just the geography of the land but the ley lines and portals to other worlds hidden from mortal eyes.",
    },
    {
      name: "Firestarter of the Phoenix",
      category: "Outdoor",
      price: 130.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/gp6zlOV",
      rating: 4.7,
      description:
        "A firestarter that ignites flames with the warmth of a phoenix's heart, ensuring a fire that burns bright and pure, warding off darkness and cold.",
    },
    {
      name: "Fragments of the Fallen Star",
      category: "Collectibles",
      price: 500.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/tNuQTW0",
      rating: 4.9,
      description:
        "Rare fragments from a star that fell into the dark realms, glowing faintly with cosmic energy, sought after by magicians and scholars.",
    },
    {
      name: "Sculpture of the Ancient Wyrm",
      category: "Collectibles",
      price: 450.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/BFKK7va",
      rating: 5.0,
      description:
        "A meticulously crafted sculpture depicting an ancient wyrm, coiled and ready to strike, its scales shimmering with an otherworldly patina.",
    },
    {
      name: "Vial of Everfrost",
      category: "Collectibles",
      price: 300.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/oDvHkvX",
      rating: 4.8,
      description:
        "A sealed vial containing frost from the coldest place in the underworld, never melting and chilling to the touch, a marvel of the natural and supernatural world.",
    },
    {
      name: "Tome of Forbidden Knowledge",
      category: "Collectibles",
      price: 1000.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/4C8Kt1N",
      rating: 5.0,
      description:
        "An ancient tome that contains spells and knowledge long forbidden, the pages whispering dark secrets to those who dare to read them.",
    },
    {
      name: "Locket of the Phantom Queen",
      category: "Collectibles",
      price: 400.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/x0tIZj2",
      rating: 4.7,
      description:
        "A locket once belonging to the Phantom Queen, containing a portrait that shifts and changes, rumored to bestow protection and curses in equal measure.",
    },
    {
      name: "Cursed Pirate Coin",
      category: "Collectibles",
      price: 350.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/EOnKzG1",
      rating: 4.9,
      description:
        "An ancient coin cursed with the luck of a damned pirate crew, bringing fortune and doom to those who possess it, encased in a crystal for safety.",
    },
    {
      name: "Draconic Scale Set",
      category: "Collectibles",
      price: 600.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/ial57BX",
      rating: 5.0,
      description:
        "A set of scales from a legendary dragon, each imbued with different elemental powers, displayed in an enchanted case that suppresses their volatile magic.",
    },
    {
      name: "Feather of the Griffin",
      category: "Collectibles",
      price: 250.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/LmZ6Cvi",
      rating: 4.8,
      description:
        "A rare feather from a griffin, symbolizing courage and strength, mounted and preserved under glass to retain its enchantment.",
    },
    {
      name: "Crystal of the Deep",
      category: "Collectibles",
      price: 550.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/mDbfHeO",
      rating: 4.9,
      description:
        "A luminous crystal from the deepest trench of the ocean, glowing with a light that seems to pulse with the heartbeat of the sea.",
    },
    {
      name: "Orb of Nightmares",
      category: "Collectibles",
      price: 800.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/bShWvom",
      rating: 5.0,
      description:
        "An orb that swirls with the essence of captured nightmares, a darkly fascinating artifact that promises insight into the fears of all who gaze into it.",
    },
    {
      name: "Dew of the Darkwood",
      category: "Beverages",
      price: 12.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/hWSnE4X",
      rating: 4.8,
      description:
        "A refreshing drink collected from the leaves of the Darkwood Forest at midnight, imbued with the essence of moonlight and mystery.",
    },
    {
      name: "Brew of the Eldritch",
      category: "Beverages",
      price: 15.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/213B58t",
      rating: 4.9,
      description:
        "A dark, potent brew that tingles the senses, made from ancient grains whispered to be harvested from fields beyond the mortal realm.",
    },
    {
      name: "Potion of Liquid Shadows",
      category: "Beverages",
      price: 18.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/uyIq2MJ",
      rating: 5.0,
      description:
        "A mesmerizing beverage that shimmers with a darkness, offering a taste of the night sky and the thrill of unseen worlds.",
    },
    {
      name: "Tears of the Phoenix",
      category: "Beverages",
      price: 20.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/DK8wT4V",
      rating: 4.7,
      description:
        "A fiery liquor made from a mythical phoenix's tears, granting warmth and a burst of energy to those brave enough to drink it.",
    },
    {
      name: "Goblin's Grog",
      category: "Beverages",
      price: 10.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/wnb7eMd",
      rating: 4.5,
      description:
        "A mischievous and bold drink, crafted from a secret goblin recipe, known for its unpredictable effects and explosive flavors.",
    },
    {
      name: "Mystic Mead of the Minstrel",
      category: "Beverages",
      price: 14.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/N2v3hV4",
      rating: 4.8,
      description:
        "An enchanting mead infused with the magic of ancient songs, each sip evokes tales of heroism and heartbreak from forgotten ages.",
    },
    {
      name: "Siren's Serenade",
      category: "Beverages",
      price: 22.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/OBfBiZu",
      rating: 4.9,
      description:
        "A captivating cocktail that echoes the allure of the siren's call, blending the sweetness of the sea with a hint of perilous charm.",
    },
    {
      name: "Witch's Brew Coffee",
      category: "Beverages",
      price: 8.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/MMB6o9G",
      rating: 4.6,
      description:
        "A coffee so dark and rich, it's rumored to be brewed in cauldrons by moonlight, offering visions of the future in its steam.",
    },
    {
      name: "Vampire's Vintage",
      category: "Beverages",
      price: 25.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/zPMDwIT",
      rating: 5.0,
      description:
        "A wine as red as blood, aged in coffins instead of barrels, providing an immortal taste of nights filled with mystery and longing.",
    },
    {
      name: "Elixir of the Luminous",
      category: "Beverages",
      price: 30.0,
      inStock: true,
      quantity: 10,
      imageUrl: "https://imgur.com/wRz0tet",
      rating: 4.7,
      description:
        "A luminescent drink that glows with an ethereal light, offering clarity of mind and a spark of creativity to those who partake.",
    })
  ];
}
