module.exports = [
  {
    username: "GandalfTheGrey",
    password: "YouShallNotPass!",
    email: "gandalf@middleearth.net",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img924/4623/lWaodb.png",
  },
  {
    username: "HarryPotter",
    password: "Alohomora123",
    email: "harry@hogwarts.com",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img923/9411/Xjtfjr.png",
  },
  {
    username: "DaenerysStormborn",
    password: "Dracarys2023",
    email: "daenerys@dragonstone.com",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img924/9788/11qolF.png",
  },
  {
    username: "FrodoBaggins",
    password: "TheOneRingToRuleThemAll",
    email: "frodo@shire.com",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img923/8791/HMCJa4.png",
  },
  {
    username: "JonSnow",
    password: "IKnowNothing18",
    email: "jon@nightswatch.org",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img922/4664/usC9r3.png",
  },
  {
    username: "Aragorn",
    password: "ReturnOfTheKing",
    email: "aragorn@gondor.gov",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img923/7633/L6nv6p.png",
  },
  {
    username: "HermioneGranger",
    password: "LeviosaNotLeviosA",
    email: "hermione@hogwarts.com",
    moneyNum: 10.0,
    userImageUrl: "",
  },
  {
    username: "TyrionLannister",
    password: "IDrinkAndIKnowThings",
    email: "tyrion@casterlyrock.gov",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img924/6378/9nFiwc.png",
  },
  {
    username: "Legolas",
    password: "BowAndArrowMaster",
    email: "legolas@woodlandrealm.elf",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img923/2042/6ZjSN3.png",
  },
  {
    username: "BilboBaggins",
    password: "TheGreatestLittleHobbitOfThemAll",
    email: "bilbo@shire.com",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img924/9206/CNrB8B.png",
  },
];
