module.exports = [
  {
    firstName: "Gandalf",
    lastName: "The Grey",
    address: "9 Firebeard Lane",
    city: "Greyhaven",
    state: "Misty Mountains",
    zipcode: "77777",
    username: "GandalfTheGrey",
    password: "YouShallNotPass!",
    email: "gandalf@middleearth.net",
    moneyNum: 10.0,
    userImageUrl: "https://imagizer.imageshack.com/img924/4623/lWaodb.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Harry",
    lastName: "Potter",
    address: "The Cupboard Under the Stairs, 4 Privet Drive",
    city: "Little Whinging",
    state: "Surrey",
    zipcode: "HP1 1HR",
    username: "HarryPotter",
    password: "Alohomora123",
    email: "harry@hogwarts.com",
    moneyNum: 10.01,
    userImageUrl: "https://imagizer.imageshack.com/img923/9411/Xjtfjr.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Daenerys",
    lastName:
      "Stormborn of the House Targaryen, First of Her Name, Queen of the Andals, the Rhoynar, and the First Men, Lady of the Seven Kingdoms, and Protector of the Realm",
    address: "Dragonstone Keep",
    city: "Dragonstone",
    state: "The Crownlands",
    zipcode: "541168",
    username: "DaenerysStormborn",
    password: "Dracarys2023",
    email: "daenerys@dragonstone.com",
    moneyNum: 10.02,
    userImageUrl: "https://imagizer.imageshack.com/img924/9788/11qolF.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Frodo",
    lastName: "Baggins",
    address: "Bag End, Hobbiton",
    city: "The Shire",
    state: "Eriador",
    zipcode: "00001",
    username: "FrodoBaggins",
    password: "TheOneRingToRuleThemAll",
    email: "frodo@shire.com",
    moneyNum: 10.02,
    userImageUrl: "https://imagizer.imageshack.com/img923/8791/HMCJa4.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Jon",
    lastName: "Snow",
    username: "JonSnow",
    address: "Castle Black, The Wall",
    city: "The North",
    state: "Westeros",
    zipcode: "99999",
    password: "IKnowNothing18",
    email: "jon@nightswatch.org",
    moneyNum: 10.03,
    userImageUrl: "https://imagizer.imageshack.com/img922/4664/usC9r3.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Aragorn II",
    lastName: "son of Arathorn",
    address: "Ranger's Lodge, Imladris",
    city: "Rivendell",
    state: "Eriador",
    zipcode: "13895",
    username: "Argorn",
    password: "ReturnOfTheKing",
    email: "aragorn@gondor.gov",
    moneyNum: 10.04,
    userImageUrl: "https://imagizer.imageshack.com/img923/7633/L6nv6p.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Hermione",
    lastName: "Granger",
    address: "The Burrow, Ottery St. Catchpole",
    city: "Devon",
    state: "England",
    zipcode: "EX11 1AB",
    username: "HermioneGranger",
    password: "LeviosaNotLeviosA",
    email: "hermione@hogwarts.com",
    moneyNum: 10.5,
    userImageUrl: "http://imageshack.com/a/img924/5742/UkLKY5.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Tyrion",
    lastName: "Lannister",
    address: "Casterly Rock, Lannisport",
    city: "The Westerlands",
    state: "Westeros",
    zipcode: "54321",
    username: "TyrionLannister",
    password: "IDrinkAndIKnowThings",
    email: "tyrion@casterlyrock.gov",
    moneyNum: 10.6,
    userImageUrl: "https://imagizer.imageshack.com/img924/6378/9nFiwc.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Legolas",
    lastName: "Greenleaf",
    address: "Greenwood Hall, Mirkwood",
    city: "Woodland Realm",
    state: "Middle-earth",
    zipcode: "45873",
    username: "Legolas",
    password: "BowAndArrowMaster",
    email: "legolas@woodlandrealm.elf",
    moneyNum: 10.7,
    userImageUrl: "https://imagizer.imageshack.com/img923/2042/6ZjSN3.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
  {
    firstName: "Bilbo",
    lastName: "Baggins",
    address: "Bag End, Hobbiton",
    city: "The Shire",
    state: "Eriador",
    zipcode: "00001",
    username: "BilboBaggins",
    password: "TheGreatestLittleHobbitOfThemAll",
    email: "bilbo@shire.com",
    moneyNum: 10.8,
    userImageUrl: "https://imagizer.imageshack.com/img924/9206/CNrB8B.png",
    favoriteProduct: "Tapestry of the World's Dawn",
  },
];
